# Generated by Django 3.1 on 2020-08-31 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysqldemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField()),
                ('girl_num', models.IntegerField()),
                ('boy_num', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('s_gender', models.BooleanField(default=True)),
                ('s_age', models.IntegerField()),
                ('conetend', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('s_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysqldemo.grades')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
